version: '3.5'

services:
  app:
    build: backend/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
    environment:
      - TZ="Europe/Berlin"
      - MC_TOKEN="loldude22changeMe"
    ports:
      - "8071:5000"

  dwd:
    build: backend/dwd
    restart: unless-stopped
    environment:
      - TZ="Europe/Berlin"
      - MC_TOKEN="loldude22changeMe"
    volumes:
      - dwd:/data
    depends_on:
      - app

  tileserver:
    build: tileserver-gl-meteocool
    restart: unless-stopped
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - dwd:/data
      - ${PWD}/tileserver-gl-meteocool/config:/etc/ts
    depends_on:
      - dwd
    ports:
      - "8070:80"

volumes:
  dwd:
