version: '3.5'

# XXX TODO:
# merge with the main docker-compose config somehow...

services:
  mongo:
    image: mongo:4
    restart: unless-stopped
    volumes:
      - mongo_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME="root"
      - MONGO_INITDB_ROOT_PASSWORD="example"
      - MONGO_INITDB_DATABASE="meteocool"

  web:
    build: frontend/
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
    ports:
      - "8040:8040"
      - "8041:8041"
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - ${PWD}/frontend/caddy/dev/Caddyfile:/etc/Caddyfile

  app:
    build: backend/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
    environment:
      - TZ="Europe/Berlin"
      - DB_CONN="mongodb://mongo:27017/"
    depends_on:
      - mongo

  dwd:
    build: backend/dwd
    restart: unless-stopped
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - dwd:/data
    depends_on:
      - app
      - mongo

  tileserver:
    build: tileserver-gl-meteocool
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
    environment:
      - TZ="Europe/Berlin"
      - MONGO_INITDB_ROOT_USERNAME="root"
      - MONGO_INITDB_ROOT_PASSWORD="example"
    volumes:
      - dwd:/data
      - ${PWD}/tileserver-gl-meteocool/config-dev:/etc/ts
    depends_on:
      - dwd


volumes:
  dwd:
  mongo_db:
